manifest:

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: 518de763a6f096ed5e217d9dd0688a11a099407a
      path: zephyr
      import:
        name-allowlist:
          - cmsis