# Copyright (c) 2024, Victor Chavez (vchavezb@protonmail.com)
# SPDX-License-Identifier: Apache-2.0

name: Build

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/ci:v0.26.15
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Initialize
        run: |
          west init --mr main
          west update -o=--depth=1 -n
      - name: Build
        run: |
          west build zbus_cpp_issue_79664 -b native_posix
